### YamlMime:ManagedReference
items:
- uid: CRMScript.NetServer.NSConfigurationAgent
  commentId: T:CRMScript.NetServer.NSConfigurationAgent
  id: NSConfigurationAgent
  so.intellisense: Void.NSConfigurationAgent
  langs:
  - crmscript
  children:
  name: NSConfigurationAgent
  nameWithType: NSConfigurationAgent
  fullName: CRMScript.NetServer.NSConfigurationAgent
  type: Class
  summary: "\nUser interface configuration - XML and other elements such as inter-client URLs.\n"
  example: 
  - "\n<pre><code>NSConfigurationAgent agent;\nagent.callMethod(arg1, arg2);</code></pre>\n"
references:
- uid: CRMScript.NetServer.NSConfigurationAgent
  commentId: T:CRMScript.NetServer.NSConfigurationAgent
  isExternal: true
  name: NSConfigurationAgent
  nameWithType: NSConfigurationAgent
  fullName: CRMScript.NetServer.NSConfigurationAgent