### YamlMime:ManagedReference
items:
- uid: CRMScript.NetServer.NSCustomerCenterConfig
  commentId: T:CRMScript.NetServer.NSCustomerCenterConfig
  id: NSCustomerCenterConfig
  so.intellisense: Void.NSCustomerCenterConfig
  langs:
  - crmscript
  children:
  name: NSCustomerCenterConfig
  nameWithType: NSCustomerCenterConfig
  fullName: CRMScript.NetServer.NSCustomerCenterConfig
  type: Class
  summary: ""
  example: 
references:
- uid: CRMScript.NetServer.NSCustomerCenterConfig
  commentId: T:CRMScript.NetServer.NSCustomerCenterConfig
  isExternal: true
  name: NSCustomerCenterConfig
  nameWithType: NSCustomerCenterConfig
  fullName: CRMScript.NetServer.NSCustomerCenterConfig