### YamlMime:ManagedReference
items:
- uid: CRMScript.NetServer.NSConfiguration
  commentId: T:CRMScript.NetServer.NSConfiguration
  id: NSConfiguration
  so.intellisense: Void.NSConfiguration
  langs:
  - crmscript
  children:
  - CRMScript.NetServer.NSConfiguration.#ctor
  name: NSConfiguration
  nameWithType: NSConfiguration
  fullName: CRMScript.NetServer.NSConfiguration
  type: Class
  summary: 
  example: 
- uid: CRMScript.NetServer.NSConfiguration.#ctor
  commentId: M:CRMScript.NetServer.NSConfiguration.#ctor
  id: '#ctor'
  so.intellisense: Void.NSConfiguration
  langs:
  - crmscript
  name: '#ctor'
  nameWithType: NSConfiguration.#ctor
  fullName: CRMScript.NetServer.NSConfiguration.#ctor
  type: Method
  summary: 
  example: 
references:
- uid: CRMScript.NetServer.NSConfiguration
  commentId: T:CRMScript.NetServer.NSConfiguration
  isExternal: true
  name: NSConfiguration
  nameWithType: NSConfiguration
  fullName: CRMScript.NetServer.NSConfiguration