### YamlMime:ManagedReference
items:
- uid: CRMScript.NetServer.NSSmsConfig
  commentId: T:CRMScript.NetServer.NSSmsConfig
  id: NSSmsConfig
  so.intellisense: Void.NSSmsConfig
  langs:
  - crmscript
  children:
  name: NSSmsConfig
  nameWithType: NSSmsConfig
  fullName: CRMScript.NetServer.NSSmsConfig
  type: Class
  summary: ""
  example: 
references:
- uid: CRMScript.NetServer.NSSmsConfig
  commentId: T:CRMScript.NetServer.NSSmsConfig
  isExternal: true
  name: NSSmsConfig
  nameWithType: NSSmsConfig
  fullName: CRMScript.NetServer.NSSmsConfig