### YamlMime:ManagedReference
items:
- uid: CRMScript.NetServer.NSAudienceConfigParameter
  commentId: T:CRMScript.NetServer.NSAudienceConfigParameter
  id: NSAudienceConfigParameter
  so.intellisense: Void.NSAudienceConfigParameter
  langs:
  - crmscript
  children:
  name: NSAudienceConfigParameter
  nameWithType: NSAudienceConfigParameter
  fullName: CRMScript.NetServer.NSAudienceConfigParameter
  type: Class
  summary: ""
  example: 
references:
- uid: CRMScript.NetServer.NSAudienceConfigParameter
  commentId: T:CRMScript.NetServer.NSAudienceConfigParameter
  isExternal: true
  name: NSAudienceConfigParameter
  nameWithType: NSAudienceConfigParameter
  fullName: CRMScript.NetServer.NSAudienceConfigParameter