### YamlMime:ManagedReference
items:
- uid: CRMScript.NetServer.NSQuoteLineConfiguration
  commentId: T:CRMScript.NetServer.NSQuoteLineConfiguration
  id: NSQuoteLineConfiguration
  so.intellisense: Void.NSQuoteLineConfiguration
  langs:
  - crmscript
  children:
  - CRMScript.NetServer.NSQuoteLineConfiguration.GetEditable
  - CRMScript.NetServer.NSQuoteLineConfiguration.GetFieldName
  - CRMScript.NetServer.NSQuoteLineConfiguration.GetInUse
  - CRMScript.NetServer.NSQuoteLineConfiguration.GetLabel
  - CRMScript.NetServer.NSQuoteLineConfiguration.GetMandatory
  - CRMScript.NetServer.NSQuoteLineConfiguration.GetQuoteLineConfigurationId
  - CRMScript.NetServer.NSQuoteLineConfiguration.GetRank
  - CRMScript.NetServer.NSQuoteLineConfiguration.GetRestrictEdit
  - CRMScript.NetServer.NSQuoteLineConfiguration.GetTooltip
  - CRMScript.NetServer.NSQuoteLineConfiguration.#ctor
  - CRMScript.NetServer.NSQuoteLineConfiguration.SetEditable
  - CRMScript.NetServer.NSQuoteLineConfiguration.SetFieldName
  - CRMScript.NetServer.NSQuoteLineConfiguration.SetInUse
  - CRMScript.NetServer.NSQuoteLineConfiguration.SetLabel
  - CRMScript.NetServer.NSQuoteLineConfiguration.SetMandatory
  - CRMScript.NetServer.NSQuoteLineConfiguration.SetQuoteLineConfigurationId
  - CRMScript.NetServer.NSQuoteLineConfiguration.SetRank
  - CRMScript.NetServer.NSQuoteLineConfiguration.SetRestrictEdit
  - CRMScript.NetServer.NSQuoteLineConfiguration.SetTooltip
  name: NSQuoteLineConfiguration
  nameWithType: NSQuoteLineConfiguration
  fullName: CRMScript.NetServer.NSQuoteLineConfiguration
  type: Class
  summary: 
  example: 
- uid: CRMScript.NetServer.NSQuoteLineConfiguration.GetEditable
  commentId: M:CRMScript.NetServer.NSQuoteLineConfiguration.GetEditable
  id: 'GetEditable'
  so.intellisense: NSQuoteLineConfiguration.GetEditable
  langs:
  - crmscript
  name: 'GetEditable'
  nameWithType: NSQuoteLineConfiguration.GetEditable
  fullName: CRMScript.NetServer.NSQuoteLineConfiguration.GetEditable
  type: Method
  summary: "\nIs this a read only field?<p></p>\n<strong>Returns:</strong>Bool<p></p>\n<pre><code>NSQuoteLineConfiguration thing;\nBool editable  = thing.GetEditable();</code></pre>\n"
  example: 
  - "\n<pre><code>NSQuoteLineConfiguration thing;\nBool editable  = thing.GetEditable();</code></pre>\n"
- uid: CRMScript.NetServer.NSQuoteLineConfiguration.GetFieldName
  commentId: M:CRMScript.NetServer.NSQuoteLineConfiguration.GetFieldName
  id: 'GetFieldName'
  so.intellisense: NSQuoteLineConfiguration.GetFieldName
  langs:
  - crmscript
  name: 'GetFieldName'
  nameWithType: NSQuoteLineConfiguration.GetFieldName
  fullName: CRMScript.NetServer.NSQuoteLineConfiguration.GetFieldName
  type: Method
  summary: "\nThe name of the field being configured, from data dictionary<p></p>\n<strong>Returns:</strong>String<p></p>\n<pre><code>NSQuoteLineConfiguration thing;\nString fieldName  = thing.GetFieldName();</code></pre>\n"
  example: 
  - "\n<pre><code>NSQuoteLineConfiguration thing;\nString fieldName  = thing.GetFieldName();</code></pre>\n"
- uid: CRMScript.NetServer.NSQuoteLineConfiguration.GetInUse
  commentId: M:CRMScript.NetServer.NSQuoteLineConfiguration.GetInUse
  id: 'GetInUse'
  so.intellisense: NSQuoteLineConfiguration.GetInUse
  langs:
  - crmscript
  name: 'GetInUse'
  nameWithType: NSQuoteLineConfiguration.GetInUse
  fullName: CRMScript.NetServer.NSQuoteLineConfiguration.GetInUse
  type: Method
  summary: "\nShould this field be displayed in the GUI?<p></p>\n<strong>Returns:</strong>Bool<p></p>\n<pre><code>NSQuoteLineConfiguration thing;\nBool inUse  = thing.GetInUse();</code></pre>\n"
  example: 
  - "\n<pre><code>NSQuoteLineConfiguration thing;\nBool inUse  = thing.GetInUse();</code></pre>\n"
- uid: CRMScript.NetServer.NSQuoteLineConfiguration.GetLabel
  commentId: M:CRMScript.NetServer.NSQuoteLineConfiguration.GetLabel
  id: 'GetLabel'
  so.intellisense: NSQuoteLineConfiguration.GetLabel
  langs:
  - crmscript
  name: 'GetLabel'
  nameWithType: NSQuoteLineConfiguration.GetLabel
  fullName: CRMScript.NetServer.NSQuoteLineConfiguration.GetLabel
  type: Method
  summary: "\nLabel resource string.<p></p>\n<strong>Returns:</strong>String<p></p>\n<pre><code>NSQuoteLineConfiguration thing;\nString label  = thing.GetLabel();</code></pre>\n"
  example: 
  - "\n<pre><code>NSQuoteLineConfiguration thing;\nString label  = thing.GetLabel();</code></pre>\n"
- uid: CRMScript.NetServer.NSQuoteLineConfiguration.GetMandatory
  commentId: M:CRMScript.NetServer.NSQuoteLineConfiguration.GetMandatory
  id: 'GetMandatory'
  so.intellisense: NSQuoteLineConfiguration.GetMandatory
  langs:
  - crmscript
  name: 'GetMandatory'
  nameWithType: NSQuoteLineConfiguration.GetMandatory
  fullName: CRMScript.NetServer.NSQuoteLineConfiguration.GetMandatory
  type: Method
  summary: "\nIs this a mandatory field?<p></p>\n<strong>Returns:</strong>Bool<p></p>\n<pre><code>NSQuoteLineConfiguration thing;\nBool mandatory  = thing.GetMandatory();</code></pre>\n"
  example: 
  - "\n<pre><code>NSQuoteLineConfiguration thing;\nBool mandatory  = thing.GetMandatory();</code></pre>\n"
- uid: CRMScript.NetServer.NSQuoteLineConfiguration.GetQuoteLineConfigurationId
  commentId: M:CRMScript.NetServer.NSQuoteLineConfiguration.GetQuoteLineConfigurationId
  id: 'GetQuoteLineConfigurationId'
  so.intellisense: NSQuoteLineConfiguration.GetQuoteLineConfigurationId
  langs:
  - crmscript
  name: 'GetQuoteLineConfigurationId'
  nameWithType: NSQuoteLineConfiguration.GetQuoteLineConfigurationId
  fullName: CRMScript.NetServer.NSQuoteLineConfiguration.GetQuoteLineConfigurationId
  type: Method
  summary: "\nPrimary key<p></p>\n<strong>Returns:</strong>Integer<p></p>\n<pre><code>NSQuoteLineConfiguration thing;\nInteger quoteLineConfigurationId  = thing.GetQuoteLineConfigurationId();</code></pre>\n"
  example: 
  - "\n<pre><code>NSQuoteLineConfiguration thing;\nInteger quoteLineConfigurationId  = thing.GetQuoteLineConfigurationId();</code></pre>\n"
- uid: CRMScript.NetServer.NSQuoteLineConfiguration.GetRank
  commentId: M:CRMScript.NetServer.NSQuoteLineConfiguration.GetRank
  id: 'GetRank'
  so.intellisense: NSQuoteLineConfiguration.GetRank
  langs:
  - crmscript
  name: 'GetRank'
  nameWithType: NSQuoteLineConfiguration.GetRank
  fullName: CRMScript.NetServer.NSQuoteLineConfiguration.GetRank
  type: Method
  summary: "\nRank of the field<p></p>\n<strong>Returns:</strong>Integer<p></p>\n<pre><code>NSQuoteLineConfiguration thing;\nInteger rank  = thing.GetRank();</code></pre>\n"
  example: 
  - "\n<pre><code>NSQuoteLineConfiguration thing;\nInteger rank  = thing.GetRank();</code></pre>\n"
- uid: CRMScript.NetServer.NSQuoteLineConfiguration.GetRestrictEdit
  commentId: M:CRMScript.NetServer.NSQuoteLineConfiguration.GetRestrictEdit
  id: 'GetRestrictEdit'
  so.intellisense: NSQuoteLineConfiguration.GetRestrictEdit
  langs:
  - crmscript
  name: 'GetRestrictEdit'
  nameWithType: NSQuoteLineConfiguration.GetRestrictEdit
  fullName: CRMScript.NetServer.NSQuoteLineConfiguration.GetRestrictEdit
  type: Method
  summary: "\nIf true, then this field cannot be set readwrite or mandatory: It's bound to be readonly<p></p>\n<strong>Returns:</strong>Bool<p></p>\n<pre><code>NSQuoteLineConfiguration thing;\nBool restrictEdit  = thing.GetRestrictEdit();</code></pre>\n"
  example: 
  - "\n<pre><code>NSQuoteLineConfiguration thing;\nBool restrictEdit  = thing.GetRestrictEdit();</code></pre>\n"
- uid: CRMScript.NetServer.NSQuoteLineConfiguration.GetTooltip
  commentId: M:CRMScript.NetServer.NSQuoteLineConfiguration.GetTooltip
  id: 'GetTooltip'
  so.intellisense: NSQuoteLineConfiguration.GetTooltip
  langs:
  - crmscript
  name: 'GetTooltip'
  nameWithType: NSQuoteLineConfiguration.GetTooltip
  fullName: CRMScript.NetServer.NSQuoteLineConfiguration.GetTooltip
  type: Method
  summary: "\nTooltip resource string.<p></p>\n<strong>Returns:</strong>String<p></p>\n<pre><code>NSQuoteLineConfiguration thing;\nString tooltip  = thing.GetTooltip();</code></pre>\n"
  example: 
  - "\n<pre><code>NSQuoteLineConfiguration thing;\nString tooltip  = thing.GetTooltip();</code></pre>\n"
- uid: CRMScript.NetServer.NSQuoteLineConfiguration.#ctor
  commentId: M:CRMScript.NetServer.NSQuoteLineConfiguration.#ctor
  id: '#ctor'
  so.intellisense: Void.NSQuoteLineConfiguration
  langs:
  - crmscript
  name: '#ctor'
  nameWithType: NSQuoteLineConfiguration.#ctor
  fullName: CRMScript.NetServer.NSQuoteLineConfiguration.#ctor
  type: Method
  summary: 
  example: 
- uid: CRMScript.NetServer.NSQuoteLineConfiguration.SetEditable
  commentId: M:CRMScript.NetServer.NSQuoteLineConfiguration.SetEditable
  id: 'SetEditable'
  so.intellisense: NSQuoteLineConfiguration.SetEditable
  langs:
  - crmscript
  name: 'SetEditable'
  nameWithType: NSQuoteLineConfiguration.SetEditable
  fullName: CRMScript.NetServer.NSQuoteLineConfiguration.SetEditable
  type: Method
  summary: "\nIs this a read only field?<p></p>\n<strong>Parameter:</strong><p></p>\n<ul><li><strong>editable</strong>Bool</li></ul><pre><code>NSQuoteLineConfiguration thing;\nBool editable;\nthing.SetEditable(editable);</code></pre>\n"
  example: 
  - "\n<pre><code>NSQuoteLineConfiguration thing;\nBool editable;\nthing.SetEditable(editable);</code></pre>\n"
- uid: CRMScript.NetServer.NSQuoteLineConfiguration.SetFieldName
  commentId: M:CRMScript.NetServer.NSQuoteLineConfiguration.SetFieldName
  id: 'SetFieldName'
  so.intellisense: NSQuoteLineConfiguration.SetFieldName
  langs:
  - crmscript
  name: 'SetFieldName'
  nameWithType: NSQuoteLineConfiguration.SetFieldName
  fullName: CRMScript.NetServer.NSQuoteLineConfiguration.SetFieldName
  type: Method
  summary: "\nThe name of the field being configured, from data dictionary<p></p>\n<strong>Parameter:</strong><p></p>\n<ul><li><strong>fieldName</strong>String</li></ul><pre><code>NSQuoteLineConfiguration thing;\nString fieldName;\nthing.SetFieldName(fieldName);</code></pre>\n"
  example: 
  - "\n<pre><code>NSQuoteLineConfiguration thing;\nString fieldName;\nthing.SetFieldName(fieldName);</code></pre>\n"
- uid: CRMScript.NetServer.NSQuoteLineConfiguration.SetInUse
  commentId: M:CRMScript.NetServer.NSQuoteLineConfiguration.SetInUse
  id: 'SetInUse'
  so.intellisense: NSQuoteLineConfiguration.SetInUse
  langs:
  - crmscript
  name: 'SetInUse'
  nameWithType: NSQuoteLineConfiguration.SetInUse
  fullName: CRMScript.NetServer.NSQuoteLineConfiguration.SetInUse
  type: Method
  summary: "\nShould this field be displayed in the GUI?<p></p>\n<strong>Parameter:</strong><p></p>\n<ul><li><strong>inUse</strong>Bool</li></ul><pre><code>NSQuoteLineConfiguration thing;\nBool inUse;\nthing.SetInUse(inUse);</code></pre>\n"
  example: 
  - "\n<pre><code>NSQuoteLineConfiguration thing;\nBool inUse;\nthing.SetInUse(inUse);</code></pre>\n"
- uid: CRMScript.NetServer.NSQuoteLineConfiguration.SetLabel
  commentId: M:CRMScript.NetServer.NSQuoteLineConfiguration.SetLabel
  id: 'SetLabel'
  so.intellisense: NSQuoteLineConfiguration.SetLabel
  langs:
  - crmscript
  name: 'SetLabel'
  nameWithType: NSQuoteLineConfiguration.SetLabel
  fullName: CRMScript.NetServer.NSQuoteLineConfiguration.SetLabel
  type: Method
  summary: "\nLabel resource string.<p></p>\n<strong>Parameter:</strong><p></p>\n<ul><li><strong>label</strong>String</li></ul><pre><code>NSQuoteLineConfiguration thing;\nString label;\nthing.SetLabel(label);</code></pre>\n"
  example: 
  - "\n<pre><code>NSQuoteLineConfiguration thing;\nString label;\nthing.SetLabel(label);</code></pre>\n"
- uid: CRMScript.NetServer.NSQuoteLineConfiguration.SetMandatory
  commentId: M:CRMScript.NetServer.NSQuoteLineConfiguration.SetMandatory
  id: 'SetMandatory'
  so.intellisense: NSQuoteLineConfiguration.SetMandatory
  langs:
  - crmscript
  name: 'SetMandatory'
  nameWithType: NSQuoteLineConfiguration.SetMandatory
  fullName: CRMScript.NetServer.NSQuoteLineConfiguration.SetMandatory
  type: Method
  summary: "\nIs this a mandatory field?<p></p>\n<strong>Parameter:</strong><p></p>\n<ul><li><strong>mandatory</strong>Bool</li></ul><pre><code>NSQuoteLineConfiguration thing;\nBool mandatory;\nthing.SetMandatory(mandatory);</code></pre>\n"
  example: 
  - "\n<pre><code>NSQuoteLineConfiguration thing;\nBool mandatory;\nthing.SetMandatory(mandatory);</code></pre>\n"
- uid: CRMScript.NetServer.NSQuoteLineConfiguration.SetQuoteLineConfigurationId
  commentId: M:CRMScript.NetServer.NSQuoteLineConfiguration.SetQuoteLineConfigurationId
  id: 'SetQuoteLineConfigurationId'
  so.intellisense: NSQuoteLineConfiguration.SetQuoteLineConfigurationId
  langs:
  - crmscript
  name: 'SetQuoteLineConfigurationId'
  nameWithType: NSQuoteLineConfiguration.SetQuoteLineConfigurationId
  fullName: CRMScript.NetServer.NSQuoteLineConfiguration.SetQuoteLineConfigurationId
  type: Method
  summary: "\nPrimary key<p></p>\n<strong>Parameter:</strong><p></p>\n<ul><li><strong>quoteLineConfigurationId</strong>Integer</li></ul><pre><code>NSQuoteLineConfiguration thing;\nInteger quoteLineConfigurationId;\nthing.SetQuoteLineConfigurationId(quoteLineConfigurationId);</code></pre>\n"
  example: 
  - "\n<pre><code>NSQuoteLineConfiguration thing;\nInteger quoteLineConfigurationId;\nthing.SetQuoteLineConfigurationId(quoteLineConfigurationId);</code></pre>\n"
- uid: CRMScript.NetServer.NSQuoteLineConfiguration.SetRank
  commentId: M:CRMScript.NetServer.NSQuoteLineConfiguration.SetRank
  id: 'SetRank'
  so.intellisense: NSQuoteLineConfiguration.SetRank
  langs:
  - crmscript
  name: 'SetRank'
  nameWithType: NSQuoteLineConfiguration.SetRank
  fullName: CRMScript.NetServer.NSQuoteLineConfiguration.SetRank
  type: Method
  summary: "\nRank of the field<p></p>\n<strong>Parameter:</strong><p></p>\n<ul><li><strong>rank</strong>Integer</li></ul><pre><code>NSQuoteLineConfiguration thing;\nInteger rank;\nthing.SetRank(rank);</code></pre>\n"
  example: 
  - "\n<pre><code>NSQuoteLineConfiguration thing;\nInteger rank;\nthing.SetRank(rank);</code></pre>\n"
- uid: CRMScript.NetServer.NSQuoteLineConfiguration.SetRestrictEdit
  commentId: M:CRMScript.NetServer.NSQuoteLineConfiguration.SetRestrictEdit
  id: 'SetRestrictEdit'
  so.intellisense: NSQuoteLineConfiguration.SetRestrictEdit
  langs:
  - crmscript
  name: 'SetRestrictEdit'
  nameWithType: NSQuoteLineConfiguration.SetRestrictEdit
  fullName: CRMScript.NetServer.NSQuoteLineConfiguration.SetRestrictEdit
  type: Method
  summary: "\nIf true, then this field cannot be set readwrite or mandatory: It's bound to be readonly<p></p>\n<strong>Parameter:</strong><p></p>\n<ul><li><strong>restrictEdit</strong>Bool</li></ul><pre><code>NSQuoteLineConfiguration thing;\nBool restrictEdit;\nthing.SetRestrictEdit(restrictEdit);</code></pre>\n"
  example: 
  - "\n<pre><code>NSQuoteLineConfiguration thing;\nBool restrictEdit;\nthing.SetRestrictEdit(restrictEdit);</code></pre>\n"
- uid: CRMScript.NetServer.NSQuoteLineConfiguration.SetTooltip
  commentId: M:CRMScript.NetServer.NSQuoteLineConfiguration.SetTooltip
  id: 'SetTooltip'
  so.intellisense: NSQuoteLineConfiguration.SetTooltip
  langs:
  - crmscript
  name: 'SetTooltip'
  nameWithType: NSQuoteLineConfiguration.SetTooltip
  fullName: CRMScript.NetServer.NSQuoteLineConfiguration.SetTooltip
  type: Method
  summary: "\nTooltip resource string.<p></p>\n<strong>Parameter:</strong><p></p>\n<ul><li><strong>tooltip</strong>String</li></ul><pre><code>NSQuoteLineConfiguration thing;\nString tooltip;\nthing.SetTooltip(tooltip);</code></pre>\n"
  example: 
  - "\n<pre><code>NSQuoteLineConfiguration thing;\nString tooltip;\nthing.SetTooltip(tooltip);</code></pre>\n"
references:
- uid: CRMScript.NetServer.NSQuoteLineConfiguration
  commentId: T:CRMScript.NetServer.NSQuoteLineConfiguration
  isExternal: true
  name: NSQuoteLineConfiguration
  nameWithType: NSQuoteLineConfiguration
  fullName: CRMScript.NetServer.NSQuoteLineConfiguration