### YamlMime:ManagedReference
items:
- uid: CRMScript.NetServer.NSMailMergeSettings
  commentId: T:CRMScript.NetServer.NSMailMergeSettings
  id: NSMailMergeSettings
  so.intellisense: Void.NSMailMergeSettings
  langs:
  - crmscript
  children:
  name: NSMailMergeSettings
  nameWithType: NSMailMergeSettings
  fullName: CRMScript.NetServer.NSMailMergeSettings
  type: Class
  summary: ""
  example: 
references:
- uid: CRMScript.NetServer.NSMailMergeSettings
  commentId: T:CRMScript.NetServer.NSMailMergeSettings
  isExternal: true
  name: NSMailMergeSettings
  nameWithType: NSMailMergeSettings
  fullName: CRMScript.NetServer.NSMailMergeSettings