### YamlMime:ManagedReference
items:
- uid: CRMScript.NetServer.NSChatWidgetSettings
  commentId: T:CRMScript.NetServer.NSChatWidgetSettings
  id: NSChatWidgetSettings
  so.intellisense: Void.NSChatWidgetSettings
  langs:
  - crmscript
  children:
  name: NSChatWidgetSettings
  nameWithType: NSChatWidgetSettings
  fullName: CRMScript.NetServer.NSChatWidgetSettings
  type: Class
  summary: ""
  example: 
references:
- uid: CRMScript.NetServer.NSChatWidgetSettings
  commentId: T:CRMScript.NetServer.NSChatWidgetSettings
  isExternal: true
  name: NSChatWidgetSettings
  nameWithType: NSChatWidgetSettings
  fullName: CRMScript.NetServer.NSChatWidgetSettings