### YamlMime:ManagedReference
items:
- uid: CRMScript.NetServer.NSArchiveConfiguration
  commentId: T:CRMScript.NetServer.NSArchiveConfiguration
  id: NSArchiveConfiguration
  so.intellisense: Void.NSArchiveConfiguration
  langs:
  - crmscript
  children:
  - CRMScript.NetServer.NSArchiveConfiguration.GetArchiveColumnInfo
  - CRMScript.NetServer.NSArchiveConfiguration.GetArchiveEntityInfo
  - CRMScript.NetServer.NSArchiveConfiguration.GetArchiveOrderByInfo
  - CRMScript.NetServer.NSArchiveConfiguration.GetOwnerKeys
  - CRMScript.NetServer.NSArchiveConfiguration.#ctor
  - CRMScript.NetServer.NSArchiveConfiguration.SetArchiveColumnInfo
  - CRMScript.NetServer.NSArchiveConfiguration.SetArchiveEntityInfo
  - CRMScript.NetServer.NSArchiveConfiguration.SetArchiveOrderByInfo
  - CRMScript.NetServer.NSArchiveConfiguration.SetOwnerKeys
  name: NSArchiveConfiguration
  nameWithType: NSArchiveConfiguration
  fullName: CRMScript.NetServer.NSArchiveConfiguration
  type: Class
  summary: 
  example: 
- uid: CRMScript.NetServer.NSArchiveConfiguration.GetArchiveColumnInfo
  commentId: M:CRMScript.NetServer.NSArchiveConfiguration.GetArchiveColumnInfo
  id: 'GetArchiveColumnInfo'
  so.intellisense: NSArchiveConfiguration.GetArchiveColumnInfo
  langs:
  - crmscript
  name: 'GetArchiveColumnInfo'
  nameWithType: NSArchiveConfiguration.GetArchiveColumnInfo
  fullName: CRMScript.NetServer.NSArchiveConfiguration.GetArchiveColumnInfo
  type: Method
  summary: "\n<strong>Returns:</strong>NSArchiveColumnInfo[]<p></p>\n<pre><code>NSArchiveConfiguration thing;\nNSArchiveColumnInfo[] archiveColumnInfo  = thing.GetArchiveColumnInfo();</code></pre>\n"
  example: 
  - "\n<pre><code>NSArchiveConfiguration thing;\nNSArchiveColumnInfo[] archiveColumnInfo  = thing.GetArchiveColumnInfo();</code></pre>\n"
- uid: CRMScript.NetServer.NSArchiveConfiguration.GetArchiveEntityInfo
  commentId: M:CRMScript.NetServer.NSArchiveConfiguration.GetArchiveEntityInfo
  id: 'GetArchiveEntityInfo'
  so.intellisense: NSArchiveConfiguration.GetArchiveEntityInfo
  langs:
  - crmscript
  name: 'GetArchiveEntityInfo'
  nameWithType: NSArchiveConfiguration.GetArchiveEntityInfo
  fullName: CRMScript.NetServer.NSArchiveConfiguration.GetArchiveEntityInfo
  type: Method
  summary: "\n<strong>Returns:</strong>NSSelectableMDOListItem[]<p></p>\n<pre><code>NSArchiveConfiguration thing;\nNSSelectableMDOListItem[] archiveEntityInfo  = thing.GetArchiveEntityInfo();</code></pre>\n"
  example: 
  - "\n<pre><code>NSArchiveConfiguration thing;\nNSSelectableMDOListItem[] archiveEntityInfo  = thing.GetArchiveEntityInfo();</code></pre>\n"
- uid: CRMScript.NetServer.NSArchiveConfiguration.GetArchiveOrderByInfo
  commentId: M:CRMScript.NetServer.NSArchiveConfiguration.GetArchiveOrderByInfo
  id: 'GetArchiveOrderByInfo'
  so.intellisense: NSArchiveConfiguration.GetArchiveOrderByInfo
  langs:
  - crmscript
  name: 'GetArchiveOrderByInfo'
  nameWithType: NSArchiveConfiguration.GetArchiveOrderByInfo
  fullName: CRMScript.NetServer.NSArchiveConfiguration.GetArchiveOrderByInfo
  type: Method
  summary: "\n<strong>Returns:</strong>NSArchiveOrderByInfo[]<p></p>\n<pre><code>NSArchiveConfiguration thing;\nNSArchiveOrderByInfo[] archiveOrderByInfo  = thing.GetArchiveOrderByInfo();</code></pre>\n"
  example: 
  - "\n<pre><code>NSArchiveConfiguration thing;\nNSArchiveOrderByInfo[] archiveOrderByInfo  = thing.GetArchiveOrderByInfo();</code></pre>\n"
- uid: CRMScript.NetServer.NSArchiveConfiguration.GetOwnerKeys
  commentId: M:CRMScript.NetServer.NSArchiveConfiguration.GetOwnerKeys
  id: 'GetOwnerKeys'
  so.intellisense: NSArchiveConfiguration.GetOwnerKeys
  langs:
  - crmscript
  name: 'GetOwnerKeys'
  nameWithType: NSArchiveConfiguration.GetOwnerKeys
  fullName: CRMScript.NetServer.NSArchiveConfiguration.GetOwnerKeys
  type: Method
  summary: "\nThe actual ownership information for the configuration that was retrieved<p></p>\n<strong>Returns:</strong>String<p></p>\n<pre><code>NSArchiveConfiguration thing;\nString ownerKeys  = thing.GetOwnerKeys();</code></pre>\n"
  example: 
  - "\n<pre><code>NSArchiveConfiguration thing;\nString ownerKeys  = thing.GetOwnerKeys();</code></pre>\n"
- uid: CRMScript.NetServer.NSArchiveConfiguration.#ctor
  commentId: M:CRMScript.NetServer.NSArchiveConfiguration.#ctor
  id: '#ctor'
  so.intellisense: Void.NSArchiveConfiguration
  langs:
  - crmscript
  name: '#ctor'
  nameWithType: NSArchiveConfiguration.#ctor
  fullName: CRMScript.NetServer.NSArchiveConfiguration.#ctor
  type: Method
  summary: 
  example: 
- uid: CRMScript.NetServer.NSArchiveConfiguration.SetArchiveColumnInfo
  commentId: M:CRMScript.NetServer.NSArchiveConfiguration.SetArchiveColumnInfo
  id: 'SetArchiveColumnInfo'
  so.intellisense: NSArchiveConfiguration.SetArchiveColumnInfo
  langs:
  - crmscript
  name: 'SetArchiveColumnInfo'
  nameWithType: NSArchiveConfiguration.SetArchiveColumnInfo
  fullName: CRMScript.NetServer.NSArchiveConfiguration.SetArchiveColumnInfo
  type: Method
  summary: "\n<strong>Parameter:</strong><p></p>\n<ul><li><strong>archiveColumnInfo</strong>NSArchiveColumnInfo[]</li></ul><pre><code>NSArchiveConfiguration thing;\nNSArchiveColumnInfo[] archiveColumnInfo;\nthing.SetArchiveColumnInfo(archiveColumnInfo);</code></pre>\n"
  example: 
  - "\n<pre><code>NSArchiveConfiguration thing;\nNSArchiveColumnInfo[] archiveColumnInfo;\nthing.SetArchiveColumnInfo(archiveColumnInfo);</code></pre>\n"
- uid: CRMScript.NetServer.NSArchiveConfiguration.SetArchiveEntityInfo
  commentId: M:CRMScript.NetServer.NSArchiveConfiguration.SetArchiveEntityInfo
  id: 'SetArchiveEntityInfo'
  so.intellisense: NSArchiveConfiguration.SetArchiveEntityInfo
  langs:
  - crmscript
  name: 'SetArchiveEntityInfo'
  nameWithType: NSArchiveConfiguration.SetArchiveEntityInfo
  fullName: CRMScript.NetServer.NSArchiveConfiguration.SetArchiveEntityInfo
  type: Method
  summary: "\n<strong>Parameter:</strong><p></p>\n<ul><li><strong>archiveEntityInfo</strong>NSSelectableMDOListItem[]</li></ul><pre><code>NSArchiveConfiguration thing;\nNSSelectableMDOListItem[] archiveEntityInfo;\nthing.SetArchiveEntityInfo(archiveEntityInfo);</code></pre>\n"
  example: 
  - "\n<pre><code>NSArchiveConfiguration thing;\nNSSelectableMDOListItem[] archiveEntityInfo;\nthing.SetArchiveEntityInfo(archiveEntityInfo);</code></pre>\n"
- uid: CRMScript.NetServer.NSArchiveConfiguration.SetArchiveOrderByInfo
  commentId: M:CRMScript.NetServer.NSArchiveConfiguration.SetArchiveOrderByInfo
  id: 'SetArchiveOrderByInfo'
  so.intellisense: NSArchiveConfiguration.SetArchiveOrderByInfo
  langs:
  - crmscript
  name: 'SetArchiveOrderByInfo'
  nameWithType: NSArchiveConfiguration.SetArchiveOrderByInfo
  fullName: CRMScript.NetServer.NSArchiveConfiguration.SetArchiveOrderByInfo
  type: Method
  summary: "\n<strong>Parameter:</strong><p></p>\n<ul><li><strong>archiveOrderByInfo</strong>NSArchiveOrderByInfo[]</li></ul><pre><code>NSArchiveConfiguration thing;\nNSArchiveOrderByInfo[] archiveOrderByInfo;\nthing.SetArchiveOrderByInfo(archiveOrderByInfo);</code></pre>\n"
  example: 
  - "\n<pre><code>NSArchiveConfiguration thing;\nNSArchiveOrderByInfo[] archiveOrderByInfo;\nthing.SetArchiveOrderByInfo(archiveOrderByInfo);</code></pre>\n"
- uid: CRMScript.NetServer.NSArchiveConfiguration.SetOwnerKeys
  commentId: M:CRMScript.NetServer.NSArchiveConfiguration.SetOwnerKeys
  id: 'SetOwnerKeys'
  so.intellisense: NSArchiveConfiguration.SetOwnerKeys
  langs:
  - crmscript
  name: 'SetOwnerKeys'
  nameWithType: NSArchiveConfiguration.SetOwnerKeys
  fullName: CRMScript.NetServer.NSArchiveConfiguration.SetOwnerKeys
  type: Method
  summary: "\nThe actual ownership information for the configuration that was retrieved<p></p>\n<strong>Parameter:</strong><p></p>\n<ul><li><strong>ownerKeys</strong>String</li></ul><pre><code>NSArchiveConfiguration thing;\nString ownerKeys;\nthing.SetOwnerKeys(ownerKeys);</code></pre>\n"
  example: 
  - "\n<pre><code>NSArchiveConfiguration thing;\nString ownerKeys;\nthing.SetOwnerKeys(ownerKeys);</code></pre>\n"
references:
- uid: CRMScript.NetServer.NSArchiveConfiguration
  commentId: T:CRMScript.NetServer.NSArchiveConfiguration
  isExternal: true
  name: NSArchiveConfiguration
  nameWithType: NSArchiveConfiguration
  fullName: CRMScript.NetServer.NSArchiveConfiguration