### YamlMime:ManagedReference
items:
- uid: CRMScript.NetServer.NSQuoteLineConfiguration
  commentId: T:CRMScript.NetServer.NSQuoteLineConfiguration
  id: NSQuoteLineConfiguration
  so.intellisense: Void.NSQuoteLineConfiguration
  langs:
  - crmscript
  children:
  name: NSQuoteLineConfiguration
  nameWithType: NSQuoteLineConfiguration
  fullName: CRMScript.NetServer.NSQuoteLineConfiguration
  type: Class
  summary: ""
  example: 
references:
- uid: CRMScript.NetServer.NSQuoteLineConfiguration
  commentId: T:CRMScript.NetServer.NSQuoteLineConfiguration
  isExternal: true
  name: NSQuoteLineConfiguration
  nameWithType: NSQuoteLineConfiguration
  fullName: CRMScript.NetServer.NSQuoteLineConfiguration