### YamlMime:ManagedReference
items:
- uid: CRMScript.NetServer.NSAudienceConfigParameterList
  commentId: T:CRMScript.NetServer.NSAudienceConfigParameterList
  id: NSAudienceConfigParameterList
  so.intellisense: Void.NSAudienceConfigParameterList
  langs:
  - crmscript
  children:
  - CRMScript.NetServer.NSAudienceConfigParameterList.#ctor
  name: NSAudienceConfigParameterList
  nameWithType: NSAudienceConfigParameterList
  fullName: CRMScript.NetServer.NSAudienceConfigParameterList
  type: Class
  summary: 
  example: 
- uid: CRMScript.NetServer.NSAudienceConfigParameterList.#ctor
  commentId: M:CRMScript.NetServer.NSAudienceConfigParameterList.#ctor
  id: '#ctor'
  so.intellisense: Void.NSAudienceConfigParameterList
  langs:
  - crmscript
  name: '#ctor'
  nameWithType: NSAudienceConfigParameterList.#ctor
  fullName: CRMScript.NetServer.NSAudienceConfigParameterList.#ctor
  type: Constructor
  summary: 
  remarks: 
  syntax: 
    content: NSAudienceConfigParameterList
  example: 
references:
- uid: CRMScript.NetServer.NSAudienceConfigParameterList
  commentId: T:CRMScript.NetServer.NSAudienceConfigParameterList
  isExternal: true
  name: NSAudienceConfigParameterList
  nameWithType: NSAudienceConfigParameterList
  fullName: CRMScript.NetServer.NSAudienceConfigParameterList