### YamlMime:ManagedReference
items:
- uid: CRMScript.NetServer.NSChatBotSettings
  commentId: T:CRMScript.NetServer.NSChatBotSettings
  id: NSChatBotSettings
  so.intellisense: Void.NSChatBotSettings
  langs:
  - crmscript
  children:
  name: NSChatBotSettings
  nameWithType: NSChatBotSettings
  fullName: CRMScript.NetServer.NSChatBotSettings
  type: Class
  summary: ""
  example: 
references:
- uid: CRMScript.NetServer.NSChatBotSettings
  commentId: T:CRMScript.NetServer.NSChatBotSettings
  isExternal: true
  name: NSChatBotSettings
  nameWithType: NSChatBotSettings
  fullName: CRMScript.NetServer.NSChatBotSettings