### YamlMime:ManagedReference
items:
- uid: CRMScript.NetServer.NSCustomerServiceConfig
  commentId: T:CRMScript.NetServer.NSCustomerServiceConfig
  id: NSCustomerServiceConfig
  so.intellisense: Void.NSCustomerServiceConfig
  langs:
  - crmscript
  children:
  name: NSCustomerServiceConfig
  nameWithType: NSCustomerServiceConfig
  fullName: CRMScript.NetServer.NSCustomerServiceConfig
  type: Class
  summary: ""
  example: 
references:
- uid: CRMScript.NetServer.NSCustomerServiceConfig
  commentId: T:CRMScript.NetServer.NSCustomerServiceConfig
  isExternal: true
  name: NSCustomerServiceConfig
  nameWithType: NSCustomerServiceConfig
  fullName: CRMScript.NetServer.NSCustomerServiceConfig