### YamlMime:ManagedReference
items:
- uid: CRMScript.NetServer.NSChatBotSettings
  commentId: T:CRMScript.NetServer.NSChatBotSettings
  id: NSChatBotSettings
  so.intellisense: Void.NSChatBotSettings
  langs:
  - crmscript
  children:
  - CRMScript.NetServer.NSChatBotSettings.GetBotMessageReceivedScriptId
  - CRMScript.NetServer.NSChatBotSettings.GetBotName
  - CRMScript.NetServer.NSChatBotSettings.GetBotRegisterScriptId
  - CRMScript.NetServer.NSChatBotSettings.GetBotSessionChangedScriptId
  - CRMScript.NetServer.NSChatBotSettings.GetBotSessionCreatedScriptId
  - CRMScript.NetServer.NSChatBotSettings.#ctor
  - CRMScript.NetServer.NSChatBotSettings.SetBotMessageReceivedScriptId
  - CRMScript.NetServer.NSChatBotSettings.SetBotName
  - CRMScript.NetServer.NSChatBotSettings.SetBotRegisterScriptId
  - CRMScript.NetServer.NSChatBotSettings.SetBotSessionChangedScriptId
  - CRMScript.NetServer.NSChatBotSettings.SetBotSessionCreatedScriptId
  name: NSChatBotSettings
  nameWithType: NSChatBotSettings
  fullName: CRMScript.NetServer.NSChatBotSettings
  type: Class
  summary: 
  example: 
- uid: CRMScript.NetServer.NSChatBotSettings.GetBotMessageReceivedScriptId
  commentId: M:CRMScript.NetServer.NSChatBotSettings.GetBotMessageReceivedScriptId
  id: 'GetBotMessageReceivedScriptId'
  so.intellisense: NSChatBotSettings.GetBotMessageReceivedScriptId
  langs:
  - crmscript
  name: 'GetBotMessageReceivedScriptId'
  nameWithType: NSChatBotSettings.GetBotMessageReceivedScriptId
  fullName: CRMScript.NetServer.NSChatBotSettings.GetBotMessageReceivedScriptId
  type: Method
  summary: "\nScript id to run when new messages received from customer.<p></p>\n<strong>Returns:</strong>Integer<p></p>\n<pre><code>NSChatBotSettings thing;\nInteger botMessageReceivedScriptId  = thing.GetBotMessageReceivedScriptId();</code></pre>\n"
  remarks: 
  syntax: 
    content: Integer GetBotMessageReceivedScriptId()
    parameters:
    return:
      type: CRMScript.Global.Integer
  example: 
  - "\n<pre><code>NSChatBotSettings thing;\nInteger botMessageReceivedScriptId  = thing.GetBotMessageReceivedScriptId();</code></pre>\n"
- uid: CRMScript.NetServer.NSChatBotSettings.GetBotName
  commentId: M:CRMScript.NetServer.NSChatBotSettings.GetBotName
  id: 'GetBotName'
  so.intellisense: NSChatBotSettings.GetBotName
  langs:
  - crmscript
  name: 'GetBotName'
  nameWithType: NSChatBotSettings.GetBotName
  fullName: CRMScript.NetServer.NSChatBotSettings.GetBotName
  type: Method
  summary: "\nChatbot name<p></p>\n<strong>Returns:</strong>String<p></p>\n<pre><code>NSChatBotSettings thing;\nString botName  = thing.GetBotName();</code></pre>\n"
  remarks: 
  syntax: 
    content: String GetBotName()
    parameters:
    return:
      type: CRMScript.Global.String
  example: 
  - "\n<pre><code>NSChatBotSettings thing;\nString botName  = thing.GetBotName();</code></pre>\n"
- uid: CRMScript.NetServer.NSChatBotSettings.GetBotRegisterScriptId
  commentId: M:CRMScript.NetServer.NSChatBotSettings.GetBotRegisterScriptId
  id: 'GetBotRegisterScriptId'
  so.intellisense: NSChatBotSettings.GetBotRegisterScriptId
  langs:
  - crmscript
  name: 'GetBotRegisterScriptId'
  nameWithType: NSChatBotSettings.GetBotRegisterScriptId
  fullName: CRMScript.NetServer.NSChatBotSettings.GetBotRegisterScriptId
  type: Method
  summary: "\nScript id to register/unregister chatbot. 0 if there is no bot<p></p>\n<strong>Returns:</strong>Integer<p></p>\n<pre><code>NSChatBotSettings thing;\nInteger botRegisterScriptId  = thing.GetBotRegisterScriptId();</code></pre>\n"
  remarks: 
  syntax: 
    content: Integer GetBotRegisterScriptId()
    parameters:
    return:
      type: CRMScript.Global.Integer
  example: 
  - "\n<pre><code>NSChatBotSettings thing;\nInteger botRegisterScriptId  = thing.GetBotRegisterScriptId();</code></pre>\n"
- uid: CRMScript.NetServer.NSChatBotSettings.GetBotSessionChangedScriptId
  commentId: M:CRMScript.NetServer.NSChatBotSettings.GetBotSessionChangedScriptId
  id: 'GetBotSessionChangedScriptId'
  so.intellisense: NSChatBotSettings.GetBotSessionChangedScriptId
  langs:
  - crmscript
  name: 'GetBotSessionChangedScriptId'
  nameWithType: NSChatBotSettings.GetBotSessionChangedScriptId
  fullName: CRMScript.NetServer.NSChatBotSettings.GetBotSessionChangedScriptId
  type: Method
  summary: "\nScript id to run when session state changes.<p></p>\n<strong>Returns:</strong>Integer<p></p>\n<pre><code>NSChatBotSettings thing;\nInteger botSessionChangedScriptId  = thing.GetBotSessionChangedScriptId();</code></pre>\n"
  remarks: 
  syntax: 
    content: Integer GetBotSessionChangedScriptId()
    parameters:
    return:
      type: CRMScript.Global.Integer
  example: 
  - "\n<pre><code>NSChatBotSettings thing;\nInteger botSessionChangedScriptId  = thing.GetBotSessionChangedScriptId();</code></pre>\n"
- uid: CRMScript.NetServer.NSChatBotSettings.GetBotSessionCreatedScriptId
  commentId: M:CRMScript.NetServer.NSChatBotSettings.GetBotSessionCreatedScriptId
  id: 'GetBotSessionCreatedScriptId'
  so.intellisense: NSChatBotSettings.GetBotSessionCreatedScriptId
  langs:
  - crmscript
  name: 'GetBotSessionCreatedScriptId'
  nameWithType: NSChatBotSettings.GetBotSessionCreatedScriptId
  fullName: CRMScript.NetServer.NSChatBotSettings.GetBotSessionCreatedScriptId
  type: Method
  summary: "\nScript id to run on new session.<p></p>\n<strong>Returns:</strong>Integer<p></p>\n<pre><code>NSChatBotSettings thing;\nInteger botSessionCreatedScriptId  = thing.GetBotSessionCreatedScriptId();</code></pre>\n"
  remarks: 
  syntax: 
    content: Integer GetBotSessionCreatedScriptId()
    parameters:
    return:
      type: CRMScript.Global.Integer
  example: 
  - "\n<pre><code>NSChatBotSettings thing;\nInteger botSessionCreatedScriptId  = thing.GetBotSessionCreatedScriptId();</code></pre>\n"
- uid: CRMScript.NetServer.NSChatBotSettings.#ctor
  commentId: M:CRMScript.NetServer.NSChatBotSettings.#ctor
  id: '#ctor'
  so.intellisense: Void.NSChatBotSettings
  langs:
  - crmscript
  name: '#ctor'
  nameWithType: NSChatBotSettings.#ctor
  fullName: CRMScript.NetServer.NSChatBotSettings.#ctor
  type: Constructor
  summary: 
  remarks: 
  syntax: 
    content: NSChatBotSettings
  example: 
- uid: CRMScript.NetServer.NSChatBotSettings.SetBotMessageReceivedScriptId
  commentId: M:CRMScript.NetServer.NSChatBotSettings.SetBotMessageReceivedScriptId
  id: 'SetBotMessageReceivedScriptId'
  so.intellisense: NSChatBotSettings.SetBotMessageReceivedScriptId
  langs:
  - crmscript
  name: 'SetBotMessageReceivedScriptId'
  nameWithType: NSChatBotSettings.SetBotMessageReceivedScriptId
  fullName: CRMScript.NetServer.NSChatBotSettings.SetBotMessageReceivedScriptId
  type: Method
  summary: "\nScript id to run when new messages received from customer.\n"
  remarks: 
  syntax: 
    content: SetBotMessageReceivedScriptId(Integer botMessageReceivedScriptId)
    parameters:
    - id: botMessageReceivedScriptId
      type: CRMScript.Global.Integer
      description: 
  example: 
  - "\n<pre><code>NSChatBotSettings thing;\nInteger botMessageReceivedScriptId;\nthing.SetBotMessageReceivedScriptId(botMessageReceivedScriptId);</code></pre>\n"
- uid: CRMScript.NetServer.NSChatBotSettings.SetBotName
  commentId: M:CRMScript.NetServer.NSChatBotSettings.SetBotName
  id: 'SetBotName'
  so.intellisense: NSChatBotSettings.SetBotName
  langs:
  - crmscript
  name: 'SetBotName'
  nameWithType: NSChatBotSettings.SetBotName
  fullName: CRMScript.NetServer.NSChatBotSettings.SetBotName
  type: Method
  summary: "\nChatbot name\n"
  remarks: 
  syntax: 
    content: SetBotName(String botName)
    parameters:
    - id: botName
      type: CRMScript.Global.String
      description: 
  example: 
  - "\n<pre><code>NSChatBotSettings thing;\nString botName;\nthing.SetBotName(botName);</code></pre>\n"
- uid: CRMScript.NetServer.NSChatBotSettings.SetBotRegisterScriptId
  commentId: M:CRMScript.NetServer.NSChatBotSettings.SetBotRegisterScriptId
  id: 'SetBotRegisterScriptId'
  so.intellisense: NSChatBotSettings.SetBotRegisterScriptId
  langs:
  - crmscript
  name: 'SetBotRegisterScriptId'
  nameWithType: NSChatBotSettings.SetBotRegisterScriptId
  fullName: CRMScript.NetServer.NSChatBotSettings.SetBotRegisterScriptId
  type: Method
  summary: "\nScript id to register/unregister chatbot. 0 if there is no bot\n"
  remarks: 
  syntax: 
    content: SetBotRegisterScriptId(Integer botRegisterScriptId)
    parameters:
    - id: botRegisterScriptId
      type: CRMScript.Global.Integer
      description: 
  example: 
  - "\n<pre><code>NSChatBotSettings thing;\nInteger botRegisterScriptId;\nthing.SetBotRegisterScriptId(botRegisterScriptId);</code></pre>\n"
- uid: CRMScript.NetServer.NSChatBotSettings.SetBotSessionChangedScriptId
  commentId: M:CRMScript.NetServer.NSChatBotSettings.SetBotSessionChangedScriptId
  id: 'SetBotSessionChangedScriptId'
  so.intellisense: NSChatBotSettings.SetBotSessionChangedScriptId
  langs:
  - crmscript
  name: 'SetBotSessionChangedScriptId'
  nameWithType: NSChatBotSettings.SetBotSessionChangedScriptId
  fullName: CRMScript.NetServer.NSChatBotSettings.SetBotSessionChangedScriptId
  type: Method
  summary: "\nScript id to run when session state changes.\n"
  remarks: 
  syntax: 
    content: SetBotSessionChangedScriptId(Integer botSessionChangedScriptId)
    parameters:
    - id: botSessionChangedScriptId
      type: CRMScript.Global.Integer
      description: 
  example: 
  - "\n<pre><code>NSChatBotSettings thing;\nInteger botSessionChangedScriptId;\nthing.SetBotSessionChangedScriptId(botSessionChangedScriptId);</code></pre>\n"
- uid: CRMScript.NetServer.NSChatBotSettings.SetBotSessionCreatedScriptId
  commentId: M:CRMScript.NetServer.NSChatBotSettings.SetBotSessionCreatedScriptId
  id: 'SetBotSessionCreatedScriptId'
  so.intellisense: NSChatBotSettings.SetBotSessionCreatedScriptId
  langs:
  - crmscript
  name: 'SetBotSessionCreatedScriptId'
  nameWithType: NSChatBotSettings.SetBotSessionCreatedScriptId
  fullName: CRMScript.NetServer.NSChatBotSettings.SetBotSessionCreatedScriptId
  type: Method
  summary: "\nScript id to run on new session.\n"
  remarks: 
  syntax: 
    content: SetBotSessionCreatedScriptId(Integer botSessionCreatedScriptId)
    parameters:
    - id: botSessionCreatedScriptId
      type: CRMScript.Global.Integer
      description: 
  example: 
  - "\n<pre><code>NSChatBotSettings thing;\nInteger botSessionCreatedScriptId;\nthing.SetBotSessionCreatedScriptId(botSessionCreatedScriptId);</code></pre>\n"
references:
- uid: CRMScript.NetServer.NSChatBotSettings
  commentId: T:CRMScript.NetServer.NSChatBotSettings
  isExternal: true
  name: NSChatBotSettings
  nameWithType: NSChatBotSettings
  fullName: CRMScript.NetServer.NSChatBotSettings
- uid: CRMScript.Global.Integer
  commentId: T:CRMScript.Global.Integer
  isExternal: true
  name: Integer
  nameWithType: Integer
  fullName: CRMScript.Global.Integer
- uid: CRMScript.Global.String
  commentId: T:CRMScript.Global.String
  isExternal: true
  name: String
  nameWithType: String
  fullName: CRMScript.Global.String