### YamlMime:ManagedReference
items:
- uid: CRMScript.NetServer.NSConfiguration
  commentId: T:CRMScript.NetServer.NSConfiguration
  id: NSConfiguration
  so.intellisense: Void.NSConfiguration
  langs:
  - crmscript
  children:
  name: NSConfiguration
  nameWithType: NSConfiguration
  fullName: CRMScript.NetServer.NSConfiguration
  type: Class
  summary: ""
  example: 
references:
- uid: CRMScript.NetServer.NSConfiguration
  commentId: T:CRMScript.NetServer.NSConfiguration
  isExternal: true
  name: NSConfiguration
  nameWithType: NSConfiguration
  fullName: CRMScript.NetServer.NSConfiguration