### YamlMime:ManagedReference
items:
- uid: CRMScript.NetServer.NSAudienceConfigParameterList
  commentId: T:CRMScript.NetServer.NSAudienceConfigParameterList
  id: NSAudienceConfigParameterList
  so.intellisense: Void.NSAudienceConfigParameterList
  langs:
  - crmscript
  children:
  name: NSAudienceConfigParameterList
  nameWithType: NSAudienceConfigParameterList
  fullName: CRMScript.NetServer.NSAudienceConfigParameterList
  type: Class
  summary: ""
  example: 
references:
- uid: CRMScript.NetServer.NSAudienceConfigParameterList
  commentId: T:CRMScript.NetServer.NSAudienceConfigParameterList
  isExternal: true
  name: NSAudienceConfigParameterList
  nameWithType: NSAudienceConfigParameterList
  fullName: CRMScript.NetServer.NSAudienceConfigParameterList