### YamlMime:ManagedReference
items:
- uid: CRMScript.NetServer.NSSmsConfig
  commentId: T:CRMScript.NetServer.NSSmsConfig
  id: NSSmsConfig
  so.intellisense: Void.NSSmsConfig
  langs:
  - crmscript
  children:
  - CRMScript.NetServer.NSSmsConfig.GetDefaultSmsCountry
  - CRMScript.NetServer.NSSmsConfig.GetNetServerSmsProvider
  - CRMScript.NetServer.NSSmsConfig.GetNsPluginConfig
  - CRMScript.NetServer.NSSmsConfig.GetNsPluginSender
  - CRMScript.NetServer.NSSmsConfig.#ctor
  - CRMScript.NetServer.NSSmsConfig.SetDefaultSmsCountry
  - CRMScript.NetServer.NSSmsConfig.SetNetServerSmsProvider
  - CRMScript.NetServer.NSSmsConfig.SetNsPluginConfig
  - CRMScript.NetServer.NSSmsConfig.SetNsPluginSender
  name: NSSmsConfig
  nameWithType: NSSmsConfig
  fullName: CRMScript.NetServer.NSSmsConfig
  type: Class
  summary: 
  example: 
- uid: CRMScript.NetServer.NSSmsConfig.GetDefaultSmsCountry
  commentId: M:CRMScript.NetServer.NSSmsConfig.GetDefaultSmsCountry
  id: 'GetDefaultSmsCountry'
  so.intellisense: NSSmsConfig.GetDefaultSmsCountry
  langs:
  - crmscript
  name: 'GetDefaultSmsCountry'
  nameWithType: NSSmsConfig.GetDefaultSmsCountry
  fullName: CRMScript.NetServer.NSSmsConfig.GetDefaultSmsCountry
  type: Method
  summary: "\nPhone prefix, will default to the current users HomeCountryId.<p></p>\n<strong>Returns:</strong>String<p></p>\n<pre><code>NSSmsConfig thing;\nString defaultSmsCountry  = thing.GetDefaultSmsCountry();</code></pre>\n"
  example: 
  - "\n<pre><code>NSSmsConfig thing;\nString defaultSmsCountry  = thing.GetDefaultSmsCountry();</code></pre>\n"
- uid: CRMScript.NetServer.NSSmsConfig.GetNetServerSmsProvider
  commentId: M:CRMScript.NetServer.NSSmsConfig.GetNetServerSmsProvider
  id: 'GetNetServerSmsProvider'
  so.intellisense: NSSmsConfig.GetNetServerSmsProvider
  langs:
  - crmscript
  name: 'GetNetServerSmsProvider'
  nameWithType: NSSmsConfig.GetNetServerSmsProvider
  fullName: CRMScript.NetServer.NSSmsConfig.GetNetServerSmsProvider
  type: Method
  summary: "\nName of the selected provider, i.e. CM, Compaya SMS (cpsms.dk), Intelecom SMS, PSWinCom SMS, SMS Teknik or TXTLocal.<p></p>\n<strong>Returns:</strong>String<p></p>\n<pre><code>NSSmsConfig thing;\nString netServerSmsProvider  = thing.GetNetServerSmsProvider();</code></pre>\n"
  example: 
  - "\n<pre><code>NSSmsConfig thing;\nString netServerSmsProvider  = thing.GetNetServerSmsProvider();</code></pre>\n"
- uid: CRMScript.NetServer.NSSmsConfig.GetNsPluginConfig
  commentId: M:CRMScript.NetServer.NSSmsConfig.GetNsPluginConfig
  id: 'GetNsPluginConfig'
  so.intellisense: NSSmsConfig.GetNsPluginConfig
  langs:
  - crmscript
  name: 'GetNsPluginConfig'
  nameWithType: NSSmsConfig.GetNsPluginConfig
  fullName: CRMScript.NetServer.NSSmsConfig.GetNsPluginConfig
  type: Method
  summary: "\nConfiguration settings provided by the SMS provider. Typically contains newline-delimited settings such as username and password.<p></p>\n<strong>Returns:</strong>StringDictionary<p></p>\n<pre><code>NSSmsConfig thing;\nStringDictionary nsPluginConfig  = thing.GetNsPluginConfig();</code></pre>\n"
  example: 
  - "\n<pre><code>NSSmsConfig thing;\nStringDictionary nsPluginConfig  = thing.GetNsPluginConfig();</code></pre>\n"
- uid: CRMScript.NetServer.NSSmsConfig.GetNsPluginSender
  commentId: M:CRMScript.NetServer.NSSmsConfig.GetNsPluginSender
  id: 'GetNsPluginSender'
  so.intellisense: NSSmsConfig.GetNsPluginSender
  langs:
  - crmscript
  name: 'GetNsPluginSender'
  nameWithType: NSSmsConfig.GetNsPluginSender
  fullName: CRMScript.NetServer.NSSmsConfig.GetNsPluginSender
  type: Method
  summary: "\nThe sender of the SMS messages. This text will appear on the recipient's mobile phone.<p></p>\n<strong>Returns:</strong>String<p></p>\n<pre><code>NSSmsConfig thing;\nString nsPluginSender  = thing.GetNsPluginSender();</code></pre>\n"
  example: 
  - "\n<pre><code>NSSmsConfig thing;\nString nsPluginSender  = thing.GetNsPluginSender();</code></pre>\n"
- uid: CRMScript.NetServer.NSSmsConfig.#ctor
  commentId: M:CRMScript.NetServer.NSSmsConfig.#ctor
  id: '#ctor'
  so.intellisense: Void.NSSmsConfig
  langs:
  - crmscript
  name: '#ctor'
  nameWithType: NSSmsConfig.#ctor
  fullName: CRMScript.NetServer.NSSmsConfig.#ctor
  type: Method
  summary: 
  example: 
- uid: CRMScript.NetServer.NSSmsConfig.SetDefaultSmsCountry
  commentId: M:CRMScript.NetServer.NSSmsConfig.SetDefaultSmsCountry
  id: 'SetDefaultSmsCountry'
  so.intellisense: NSSmsConfig.SetDefaultSmsCountry
  langs:
  - crmscript
  name: 'SetDefaultSmsCountry'
  nameWithType: NSSmsConfig.SetDefaultSmsCountry
  fullName: CRMScript.NetServer.NSSmsConfig.SetDefaultSmsCountry
  type: Method
  summary: "\nPhone prefix, will default to the current users HomeCountryId.<p></p>\n<strong>Parameter:</strong><p></p>\n<ul><li><strong>defaultSmsCountry</strong>String</li></ul><pre><code>NSSmsConfig thing;\nString defaultSmsCountry;\nthing.SetDefaultSmsCountry(defaultSmsCountry);</code></pre>\n"
  example: 
  - "\n<pre><code>NSSmsConfig thing;\nString defaultSmsCountry;\nthing.SetDefaultSmsCountry(defaultSmsCountry);</code></pre>\n"
- uid: CRMScript.NetServer.NSSmsConfig.SetNetServerSmsProvider
  commentId: M:CRMScript.NetServer.NSSmsConfig.SetNetServerSmsProvider
  id: 'SetNetServerSmsProvider'
  so.intellisense: NSSmsConfig.SetNetServerSmsProvider
  langs:
  - crmscript
  name: 'SetNetServerSmsProvider'
  nameWithType: NSSmsConfig.SetNetServerSmsProvider
  fullName: CRMScript.NetServer.NSSmsConfig.SetNetServerSmsProvider
  type: Method
  summary: "\nName of the selected provider, i.e. CM, Compaya SMS (cpsms.dk), Intelecom SMS, PSWinCom SMS, SMS Teknik or TXTLocal.<p></p>\n<strong>Parameter:</strong><p></p>\n<ul><li><strong>netServerSmsProvider</strong>String</li></ul><pre><code>NSSmsConfig thing;\nString netServerSmsProvider;\nthing.SetNetServerSmsProvider(netServerSmsProvider);</code></pre>\n"
  example: 
  - "\n<pre><code>NSSmsConfig thing;\nString netServerSmsProvider;\nthing.SetNetServerSmsProvider(netServerSmsProvider);</code></pre>\n"
- uid: CRMScript.NetServer.NSSmsConfig.SetNsPluginConfig
  commentId: M:CRMScript.NetServer.NSSmsConfig.SetNsPluginConfig
  id: 'SetNsPluginConfig'
  so.intellisense: NSSmsConfig.SetNsPluginConfig
  langs:
  - crmscript
  name: 'SetNsPluginConfig'
  nameWithType: NSSmsConfig.SetNsPluginConfig
  fullName: CRMScript.NetServer.NSSmsConfig.SetNsPluginConfig
  type: Method
  summary: "\nConfiguration settings provided by the SMS provider. Typically contains newline-delimited settings such as username and password.<p></p>\n<strong>Parameter:</strong><p></p>\n<ul><li><strong>nsPluginConfig</strong>StringDictionary</li></ul><pre><code>NSSmsConfig thing;\nStringDictionary nsPluginConfig;\nthing.SetNsPluginConfig(nsPluginConfig);</code></pre>\n"
  example: 
  - "\n<pre><code>NSSmsConfig thing;\nStringDictionary nsPluginConfig;\nthing.SetNsPluginConfig(nsPluginConfig);</code></pre>\n"
- uid: CRMScript.NetServer.NSSmsConfig.SetNsPluginSender
  commentId: M:CRMScript.NetServer.NSSmsConfig.SetNsPluginSender
  id: 'SetNsPluginSender'
  so.intellisense: NSSmsConfig.SetNsPluginSender
  langs:
  - crmscript
  name: 'SetNsPluginSender'
  nameWithType: NSSmsConfig.SetNsPluginSender
  fullName: CRMScript.NetServer.NSSmsConfig.SetNsPluginSender
  type: Method
  summary: "\nThe sender of the SMS messages. This text will appear on the recipient's mobile phone.<p></p>\n<strong>Parameter:</strong><p></p>\n<ul><li><strong>nsPluginSender</strong>String</li></ul><pre><code>NSSmsConfig thing;\nString nsPluginSender;\nthing.SetNsPluginSender(nsPluginSender);</code></pre>\n"
  example: 
  - "\n<pre><code>NSSmsConfig thing;\nString nsPluginSender;\nthing.SetNsPluginSender(nsPluginSender);</code></pre>\n"
references:
- uid: CRMScript.NetServer.NSSmsConfig
  commentId: T:CRMScript.NetServer.NSSmsConfig
  isExternal: true
  name: NSSmsConfig
  nameWithType: NSSmsConfig
  fullName: CRMScript.NetServer.NSSmsConfig