### YamlMime:ManagedReference
items:
- uid: CRMScript.NetServer.NSArchiveConfiguration
  commentId: T:CRMScript.NetServer.NSArchiveConfiguration
  id: NSArchiveConfiguration
  so.intellisense: Void.NSArchiveConfiguration
  langs:
  - crmscript
  children:
  name: NSArchiveConfiguration
  nameWithType: NSArchiveConfiguration
  fullName: CRMScript.NetServer.NSArchiveConfiguration
  type: Class
  summary: ""
  example: 
references:
- uid: CRMScript.NetServer.NSArchiveConfiguration
  commentId: T:CRMScript.NetServer.NSArchiveConfiguration
  isExternal: true
  name: NSArchiveConfiguration
  nameWithType: NSArchiveConfiguration
  fullName: CRMScript.NetServer.NSArchiveConfiguration