### YamlMime:ManagedReference
items:
- uid: CRMScript.NetServer.NSSaintConfiguration
  commentId: T:CRMScript.NetServer.NSSaintConfiguration
  id: NSSaintConfiguration
  so.intellisense: Void.NSSaintConfiguration
  langs:
  - crmscript
  children:
  name: NSSaintConfiguration
  nameWithType: NSSaintConfiguration
  fullName: CRMScript.NetServer.NSSaintConfiguration
  type: Class
  summary: ""
  example: 
references:
- uid: CRMScript.NetServer.NSSaintConfiguration
  commentId: T:CRMScript.NetServer.NSSaintConfiguration
  isExternal: true
  name: NSSaintConfiguration
  nameWithType: NSSaintConfiguration
  fullName: CRMScript.NetServer.NSSaintConfiguration