### YamlMime:ManagedReference
items:
- uid: CRMScript.NetServer.NSCustomerServiceConfig
  commentId: T:CRMScript.NetServer.NSCustomerServiceConfig
  id: NSCustomerServiceConfig
  so.intellisense: Void.NSCustomerServiceConfig
  langs:
  - crmscript
  children:
  - CRMScript.NetServer.NSCustomerServiceConfig.#ctor()
  name: NSCustomerServiceConfig
  nameWithType: NSCustomerServiceConfig
  fullName: CRMScript.NetServer.NSCustomerServiceConfig
  type: Class
  summary: 
  example: 
- uid: CRMScript.NetServer.NSCustomerServiceConfig.#ctor()
  commentId: M:CRMScript.NetServer.NSCustomerServiceConfig.#ctor()
  id: '#ctor()'
  so.intellisense: Void.NSCustomerServiceConfig
  langs:
  - crmscript
  name: '#ctor()'
  nameWithType: NSCustomerServiceConfig.#ctor()
  fullName: CRMScript.NetServer.NSCustomerServiceConfig.#ctor()
  type: Constructor
  summary: 
  remarks: 
  syntax: 
    content: NSCustomerServiceConfig
  example: 
references:
- uid: CRMScript.NetServer.NSCustomerServiceConfig
  commentId: T:CRMScript.NetServer.NSCustomerServiceConfig
  isExternal: true
  name: NSCustomerServiceConfig
  nameWithType: NSCustomerServiceConfig
  fullName: CRMScript.NetServer.NSCustomerServiceConfig