### YamlMime:ManagedReference
items:
- uid: CRMScript.NetServer.NSArchiveConfiguration
  commentId: T:CRMScript.NetServer.NSArchiveConfiguration
  id: NSArchiveConfiguration
  so.intellisense: Void.NSArchiveConfiguration
  langs:
  - crmscript
  children:
  - CRMScript.NetServer.NSArchiveConfiguration.GetArchiveColumnInfo()
  - CRMScript.NetServer.NSArchiveConfiguration.GetArchiveEntityInfo()
  - CRMScript.NetServer.NSArchiveConfiguration.GetArchiveOrderByInfo()
  - CRMScript.NetServer.NSArchiveConfiguration.GetOwnerKeys()
  - CRMScript.NetServer.NSArchiveConfiguration.#ctor
  - CRMScript.NetServer.NSArchiveConfiguration.SetArchiveColumnInfo()
  - CRMScript.NetServer.NSArchiveConfiguration.SetArchiveEntityInfo()
  - CRMScript.NetServer.NSArchiveConfiguration.SetArchiveOrderByInfo()
  - CRMScript.NetServer.NSArchiveConfiguration.SetOwnerKeys(String)
  name: NSArchiveConfiguration
  nameWithType: NSArchiveConfiguration
  fullName: CRMScript.NetServer.NSArchiveConfiguration
  type: Class
  summary: 
  example: 
- uid: CRMScript.NetServer.NSArchiveConfiguration.GetArchiveColumnInfo()
  commentId: M:CRMScript.NetServer.NSArchiveConfiguration.GetArchiveColumnInfo()
  id: 'GetArchiveColumnInfo()'
  so.intellisense: NSArchiveConfiguration.GetArchiveColumnInfo
  langs:
  - crmscript
  name: 'GetArchiveColumnInfo()'
  nameWithType: NSArchiveConfiguration.GetArchiveColumnInfo()
  fullName: CRMScript.NetServer.NSArchiveConfiguration.GetArchiveColumnInfo()
  type: Method
  summary: "\n<strong>Returns:</strong>NSArchiveColumnInfo[]<p></p>\n<pre><code>NSArchiveConfiguration thing;\nNSArchiveColumnInfo[] archiveColumnInfo = thing.GetArchiveColumnInfo();</code></pre>\n"
  remarks: 
  syntax: 
    content: NSArchiveColumnInfo[] GetArchiveColumnInfo()
    parameters:
    return:
      type: CRMScript.NetServer.NSArchiveColumnInfo[]
  example: 
  - "\n<pre><code>NSArchiveConfiguration thing;\nNSArchiveColumnInfo[] archiveColumnInfo = thing.GetArchiveColumnInfo();</code></pre>\n"
- uid: CRMScript.NetServer.NSArchiveConfiguration.GetArchiveEntityInfo()
  commentId: M:CRMScript.NetServer.NSArchiveConfiguration.GetArchiveEntityInfo()
  id: 'GetArchiveEntityInfo()'
  so.intellisense: NSArchiveConfiguration.GetArchiveEntityInfo
  langs:
  - crmscript
  name: 'GetArchiveEntityInfo()'
  nameWithType: NSArchiveConfiguration.GetArchiveEntityInfo()
  fullName: CRMScript.NetServer.NSArchiveConfiguration.GetArchiveEntityInfo()
  type: Method
  summary: "\n<strong>Returns:</strong>NSSelectableMDOListItem[]<p></p>\n<pre><code>NSArchiveConfiguration thing;\nNSSelectableMDOListItem[] archiveEntityInfo = thing.GetArchiveEntityInfo();</code></pre>\n"
  remarks: 
  syntax: 
    content: NSSelectableMDOListItem[] GetArchiveEntityInfo()
    parameters:
    return:
      type: CRMScript.NetServer.NSSelectableMDOListItem[]
  example: 
  - "\n<pre><code>NSArchiveConfiguration thing;\nNSSelectableMDOListItem[] archiveEntityInfo = thing.GetArchiveEntityInfo();</code></pre>\n"
- uid: CRMScript.NetServer.NSArchiveConfiguration.GetArchiveOrderByInfo()
  commentId: M:CRMScript.NetServer.NSArchiveConfiguration.GetArchiveOrderByInfo()
  id: 'GetArchiveOrderByInfo()'
  so.intellisense: NSArchiveConfiguration.GetArchiveOrderByInfo
  langs:
  - crmscript
  name: 'GetArchiveOrderByInfo()'
  nameWithType: NSArchiveConfiguration.GetArchiveOrderByInfo()
  fullName: CRMScript.NetServer.NSArchiveConfiguration.GetArchiveOrderByInfo()
  type: Method
  summary: "\n<strong>Returns:</strong>NSArchiveOrderByInfo[]<p></p>\n<pre><code>NSArchiveConfiguration thing;\nNSArchiveOrderByInfo[] archiveOrderByInfo = thing.GetArchiveOrderByInfo();</code></pre>\n"
  remarks: 
  syntax: 
    content: NSArchiveOrderByInfo[] GetArchiveOrderByInfo()
    parameters:
    return:
      type: CRMScript.NetServer.NSArchiveOrderByInfo[]
  example: 
  - "\n<pre><code>NSArchiveConfiguration thing;\nNSArchiveOrderByInfo[] archiveOrderByInfo = thing.GetArchiveOrderByInfo();</code></pre>\n"
- uid: CRMScript.NetServer.NSArchiveConfiguration.GetOwnerKeys()
  commentId: M:CRMScript.NetServer.NSArchiveConfiguration.GetOwnerKeys()
  id: 'GetOwnerKeys()'
  so.intellisense: NSArchiveConfiguration.GetOwnerKeys
  langs:
  - crmscript
  name: 'GetOwnerKeys()'
  nameWithType: NSArchiveConfiguration.GetOwnerKeys()
  fullName: CRMScript.NetServer.NSArchiveConfiguration.GetOwnerKeys()
  type: Method
  summary: "\nThe actual ownership information for the configuration that was retrieved<p></p>\n<strong>Returns:</strong>String<p></p>\n<pre><code>NSArchiveConfiguration thing;\nString ownerKeys = thing.GetOwnerKeys();</code></pre>\n"
  remarks: 
  syntax: 
    content: String GetOwnerKeys()
    parameters:
    return:
      type: CRMScript.Global.String
  example: 
  - "\n<pre><code>NSArchiveConfiguration thing;\nString ownerKeys = thing.GetOwnerKeys();</code></pre>\n"
- uid: CRMScript.NetServer.NSArchiveConfiguration.#ctor
  commentId: M:CRMScript.NetServer.NSArchiveConfiguration.#ctor
  id: '#ctor'
  so.intellisense: Void.NSArchiveConfiguration
  langs:
  - crmscript
  name: '#ctor'
  nameWithType: NSArchiveConfiguration.#ctor
  fullName: CRMScript.NetServer.NSArchiveConfiguration.#ctor
  type: Constructor
  summary: 
  remarks: 
  syntax: 
    content: NSArchiveConfiguration
  example: 
- uid: CRMScript.NetServer.NSArchiveConfiguration.SetArchiveColumnInfo()
  commentId: M:CRMScript.NetServer.NSArchiveConfiguration.SetArchiveColumnInfo()
  id: 'SetArchiveColumnInfo()'
  so.intellisense: NSArchiveConfiguration.SetArchiveColumnInfo
  langs:
  - crmscript
  name: 'SetArchiveColumnInfo()'
  nameWithType: NSArchiveConfiguration.SetArchiveColumnInfo()
  fullName: CRMScript.NetServer.NSArchiveConfiguration.SetArchiveColumnInfo()
  type: Method
  summary: 
  remarks: 
  syntax: 
    content: SetArchiveColumnInfo(NSArchiveColumnInfo[] archiveColumnInfo)
    parameters:
  example: 
  - "\n<pre><code>NSArchiveConfiguration thing;\nNSArchiveColumnInfo[] archiveColumnInfo;\nthing.SetArchiveColumnInfo(archiveColumnInfo);</code></pre>\n"
- uid: CRMScript.NetServer.NSArchiveConfiguration.SetArchiveEntityInfo()
  commentId: M:CRMScript.NetServer.NSArchiveConfiguration.SetArchiveEntityInfo()
  id: 'SetArchiveEntityInfo()'
  so.intellisense: NSArchiveConfiguration.SetArchiveEntityInfo
  langs:
  - crmscript
  name: 'SetArchiveEntityInfo()'
  nameWithType: NSArchiveConfiguration.SetArchiveEntityInfo()
  fullName: CRMScript.NetServer.NSArchiveConfiguration.SetArchiveEntityInfo()
  type: Method
  summary: 
  remarks: 
  syntax: 
    content: SetArchiveEntityInfo(NSSelectableMDOListItem[] archiveEntityInfo)
    parameters:
  example: 
  - "\n<pre><code>NSArchiveConfiguration thing;\nNSSelectableMDOListItem[] archiveEntityInfo;\nthing.SetArchiveEntityInfo(archiveEntityInfo);</code></pre>\n"
- uid: CRMScript.NetServer.NSArchiveConfiguration.SetArchiveOrderByInfo()
  commentId: M:CRMScript.NetServer.NSArchiveConfiguration.SetArchiveOrderByInfo()
  id: 'SetArchiveOrderByInfo()'
  so.intellisense: NSArchiveConfiguration.SetArchiveOrderByInfo
  langs:
  - crmscript
  name: 'SetArchiveOrderByInfo()'
  nameWithType: NSArchiveConfiguration.SetArchiveOrderByInfo()
  fullName: CRMScript.NetServer.NSArchiveConfiguration.SetArchiveOrderByInfo()
  type: Method
  summary: 
  remarks: 
  syntax: 
    content: SetArchiveOrderByInfo(NSArchiveOrderByInfo[] archiveOrderByInfo)
    parameters:
  example: 
  - "\n<pre><code>NSArchiveConfiguration thing;\nNSArchiveOrderByInfo[] archiveOrderByInfo;\nthing.SetArchiveOrderByInfo(archiveOrderByInfo);</code></pre>\n"
- uid: CRMScript.NetServer.NSArchiveConfiguration.SetOwnerKeys(String)
  commentId: M:CRMScript.NetServer.NSArchiveConfiguration.SetOwnerKeys(String)
  id: 'SetOwnerKeys(String)'
  so.intellisense: NSArchiveConfiguration.SetOwnerKeys
  langs:
  - crmscript
  name: 'SetOwnerKeys(String)'
  nameWithType: NSArchiveConfiguration.SetOwnerKeys(String)
  fullName: CRMScript.NetServer.NSArchiveConfiguration.SetOwnerKeys(String)
  type: Method
  summary: "\nThe actual ownership information for the configuration that was retrieved\n"
  remarks: 
  syntax: 
    content: SetOwnerKeys(String ownerKeys)
    parameters:
    - id: ownerKeys
      type: CRMScript.Global.String
      description: 
  example: 
  - "\n<pre><code>NSArchiveConfiguration thing;\nString ownerKeys;\nthing.SetOwnerKeys(ownerKeys);</code></pre>\n"
references:
- uid: CRMScript.NetServer.NSArchiveConfiguration
  commentId: T:CRMScript.NetServer.NSArchiveConfiguration
  isExternal: true
  name: NSArchiveConfiguration
  nameWithType: NSArchiveConfiguration
  fullName: CRMScript.NetServer.NSArchiveConfiguration
- uid: CRMScript.NetServer.NSArchiveColumnInfo[]
  isExternal: true
  name: NSArchiveColumnInfo[]
  nameWithType: NSArchiveColumnInfo[]
  fullName: CRMScript.NetServer.NSArchiveColumnInfo[]
  spec.crmscript:
  - uid: CRMScript.NetServer.NSArchiveColumnInfo
    isExternal: true
    name: NSArchiveColumnInfo
    nameWithType: NSArchiveColumnInfo
    fullName: CRMScript.NetServer.NSArchiveColumnInfo
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
- uid: CRMScript.NetServer.NSArchiveColumnInfo
  commentId: T:CRMScript.NetServer.NSArchiveColumnInfo
  isExternal: true
  name: NSArchiveColumnInfo
  nameWithType: NSArchiveColumnInfo
  fullName: CRMScript.NetServer.NSArchiveColumnInfo
- uid: CRMScript.NetServer.NSSelectableMDOListItem[]
  isExternal: true
  name: NSSelectableMDOListItem[]
  nameWithType: NSSelectableMDOListItem[]
  fullName: CRMScript.NetServer.NSSelectableMDOListItem[]
  spec.crmscript:
  - uid: CRMScript.NetServer.NSSelectableMDOListItem
    isExternal: true
    name: NSSelectableMDOListItem
    nameWithType: NSSelectableMDOListItem
    fullName: CRMScript.NetServer.NSSelectableMDOListItem
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
- uid: CRMScript.NetServer.NSSelectableMDOListItem
  commentId: T:CRMScript.NetServer.NSSelectableMDOListItem
  isExternal: true
  name: NSSelectableMDOListItem
  nameWithType: NSSelectableMDOListItem
  fullName: CRMScript.NetServer.NSSelectableMDOListItem
- uid: CRMScript.NetServer.NSArchiveOrderByInfo[]
  isExternal: true
  name: NSArchiveOrderByInfo[]
  nameWithType: NSArchiveOrderByInfo[]
  fullName: CRMScript.NetServer.NSArchiveOrderByInfo[]
  spec.crmscript:
  - uid: CRMScript.NetServer.NSArchiveOrderByInfo
    isExternal: true
    name: NSArchiveOrderByInfo
    nameWithType: NSArchiveOrderByInfo
    fullName: CRMScript.NetServer.NSArchiveOrderByInfo
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
- uid: CRMScript.NetServer.NSArchiveOrderByInfo
  commentId: T:CRMScript.NetServer.NSArchiveOrderByInfo
  isExternal: true
  name: NSArchiveOrderByInfo
  nameWithType: NSArchiveOrderByInfo
  fullName: CRMScript.NetServer.NSArchiveOrderByInfo
- uid: CRMScript.Global.String
  commentId: T:CRMScript.Global.String
  isExternal: true
  name: String
  nameWithType: String
  fullName: CRMScript.Global.String